type = "directrequest"
schemaVersion = 1
name = "LW_LM_EA_bool"
externalJobID = "43309009-a154-495c-b2ed-794233e6ff56"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "<oracle address>"
evmChainID = "59144"
minIncomingConfirmations = 3
minContractPaymentLinkJuels = "100000000000000000"
observationSource = """

    decode_log  [
                type="ethabidecodelog"
                abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                data="$(jobRun.logData)"
                topics="$(jobRun.logTopics)"
                ]

    decode_cbor [
                type="cborparse"
                data="$(decode_log.data)"
                ]

    send_to_bridge [
                type="bridge" 
                name="common-http-forwarder" 
                requestData="{\\"contact-id\\":$(decode_cbor.contact),\\"url\\":$(decode_cbor.url),\\"method\\":$(decode_cbor.method),\\"headers\\":$(decode_cbor.headers),\\"body\\":$(decode_cbor.body),\\"jsonpath\\":$(decode_cbor.path),\\"jobname\\":$(jobSpec.name),\\"txnhash\\":$(jobRun.logTxHash),\\"externaljobid\\":$(jobSpec.externalJobID),\\"oracleaddress\\":$(jobRun.logAddress)}" 
                headers="[\\"secret-val-01\\", \\"\\", \\"secret-val-02\\", \\"\\", \\"secret-val-03\\", \\"\\", \\"secret-val-04\\", \\"\\", \\"secret-val-05\\", \\"\\"]"
                ]

    encode_data [
                type="ethabiencode" 
                abi="(bytes32 requestId, bool value)" 
                data="{ \\"requestId\\": $(decode_log.requestId), \\"value\\": $(send_to_bridge) }"
                ]

    encode_tx   [
                type="ethabiencode"
                abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                ]

    encode_gas_guardian_data   [
                type="ethabiencode"
                abi="fulfill(bytes32 requestId, bool value)" 
                data="{\\"requestId\\": $(decode_log.requestId), \\"value\\": $(send_to_bridge)}"
                ]

    gas_guardian [
                type="bridge" 
                name="gas-guardian" 
                requestData="{\\"contact-id\\":$(decode_cbor.contact),\\"data\\":$(encode_gas_guardian_data),\\"jobname\\":$(jobSpec.name),\\"txnhash\\":$(jobRun.logTxHash),\\"externaljobid\\":$(jobSpec.externalJobID),\\"oracleaddress\\":$(jobRun.logAddress)}" 
                headers="[\\"disable\\", \\"false\\", \\"gas-limit\\", \\"1000000\\", \\"max-loss-usd\\", \\"0\\", \\"max-loss-pct\\", \\"0\\"]"
                ]

    submit_tx   [
                type="ethtx"
                to="<oracle address>"
                data="$(encode_tx)"
                gasLimit="1000000"
                ]

    decode_log -> decode_cbor -> send_to_bridge

    send_to_bridge -> encode_data -> encode_tx
    send_to_bridge -> encode_gas_guardian_data -> gas_guardian

    encode_tx -> submit_tx
    gas_guardian -> submit_tx
"""