type = "directrequest"
schemaVersion = 1
name = "LW_MM_DR_Get_Uint256"
externalJobID = "f4821ba2-e8ae-4ddb-a52e-a6860887df96"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0x9F306bB9da1a12bF1590d3EA65e038fC414d6b68"
minContractPaymentLinkJuels = "100000000000000000"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times="$(decode_cbor.times)"]
    encode_data  [type="ethabiencode" 
                abi="(bytes32 requestId, uint256 value)" 
                data="{ \\"requestId\\": $(decode_log.requestId), \\"value\\": $(multiply) }"
                ]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x9F306bB9da1a12bF1590d3EA65e038fC414d6b68" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""