type = "directrequest"
schemaVersion = 1
name = "LW_OGT_DR_Get_Uint256_x2"
externalJobID = "fe82fb4d-0079-4483-a1cf-5ed23bd5e1b7"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0x14bc7F6Da6cA3E072793c185e01a76E62341CC61"
minContractPaymentLinkJuels = "0"
observationSource = """
       decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    decode_log -> decode_cbor
    decode_cbor -> value1
    decode_cbor -> value2
    value1          [type="http" method=GET url="$(decode_cbor.url1)" allowunrestrictednetworkaccess="false"]
    value1_parse    [type="jsonparse" path="$(decode_cbor.path1)" data="$(value1)"]
    value1_multiply [type="multiply" input="$(value1_parse)", times="$(decode_cbor.times)"]
    value1 -> value1_parse -> value1_multiply
    value2          [type="http" method=GET url="$(decode_cbor.url2)" allowunrestrictednetworkaccess="false"]
    value2_parse    [type="jsonparse" path="$(decode_cbor.path2)" data="$(value2)"]
    value2_multiply [type="multiply" input="$(value2_parse)", times="$(decode_cbor.times)"]
    value2 -> value2_parse -> value2_multiply
    value1_multiply -> encode_mwr
    value2_multiply -> encode_mwr
    // MWR API does NOT auto populate the requestID.
    encode_mwr [type="ethabiencode"
                abi="(bytes32 requestId, uint256 _value1, uint256 _value2)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"_value1\\": $(value1_multiply), \\"_value2\\": $(value2_multiply)}"
                ]
    encode_tx  [type="ethabiencode"
                abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_mwr)}"
                ]
    submit_tx  [type="ethtx" to="0x14bc7F6Da6cA3E072793c185e01a76E62341CC61" data="$(encode_tx)"]
    encode_mwr -> encode_tx -> submit_tx
"""