
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Services',
      link: {type: 'doc', id: 'jobs-and-pricing'},
      items: [
        {
          type: 'category',
          label: 'Mainnets',
          link: {type: 'doc', id: 'services/mainnets/mainnets'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'services/mainnets/jobs', 
            },
          ]
        },
        {
          type: 'category',
          label: 'Testnets',
          link: {type: 'doc', id: 'services/testnets/testnets'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'services/testnets/jobs', 
            },
          ]
        },
      ],     
    },
    {
      type: 'category',
      label: 'Knowledge Base',
      // link: {type: 'doc', id: 'services/testnets/testnets'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'knowledgebase', 
        },
      ]
    },
    'about',
    {
      type: 'link',
      label: 'Contact Us', // The link label
      href: 'https://linkwellnodes.io/Home.html#contact-us', // The external URL
    }, 
  ]
};

// module.exports = sidebars;
